### ISSUE TITLE
개설관목관리 1

### ISSUE THREAD

**Issue by SunggyuLee** [SunggyuLee/College_Management_System#12]
1. 개설과목 등록 
	> 처음에 과목명 리스트 뜨게
	> 학수번호 입력 못받고 과목명과 분반으로 합쳐서 sub2-1 같이 학수번호 만들어지도록
	> 과목당 강의시간이 겹칠수 없게
	> 강의실당 강의시간 겹치지 않게

**Comment by kimseongje3111** [comment]
제가 할게용
