### ISSUE TITLE
개설과목관리 2

### ISSUE THREAD

**Issue by SunggyuLee** [SunggyuLee/College_Management_System#13]
2. 개설과목 수정 
	> 처음에 학수번호 리스트 뜨도록
	> 수정은 학수번호 입력 후 과목명과 분반은 입력 받지 않고 강의시간 부터 입력 받도록
	> 과목당 강의시간이 겹칠수 없게
	> 강의실당 강의시간 겹치지 않게

**Comment by kimseongje3111** [comment]
제가 하겠습니당
